#it would be more devops-y to use a makefile and build a static executable but this is quick and dirty.
FROM golang:1.13.8-alpine3.11
RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN go mod download
RUN go build -v
CMD [ "/app/sezzle-interview" ]
